#!/usr/bin/env python3
"""PreToolUse (Edit/Write): deny editing requirements.txt when a pyproject.toml is nearby.

requirements.txt is usually `uv export`-generated — steer edits to pyproject.toml.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib import hook_io  # noqa: E402


def decide(inp: hook_io.HookInput) -> str | None:
    if not inp.is_tool("Edit", "Write"):
        return None
    target = (inp.tool_input or {}).get("file_path", "")
    if not target or Path(target).name != "requirements.txt":
        return None
    parent = Path(target).parent
    if not parent.is_absolute():
        return None
    if not any((d / "pyproject.toml").exists() for d in (parent, parent.parent)):
        return None
    return (
        f"⚠️  `{target}` is typically auto-generated by `uv export`, not hand-edited.\n"
        "Edit `pyproject.toml` instead, then run `uv lock` + `uv sync`.\n"
        "If CI needs requirements.txt, regenerate via `uv export` after editing pyproject.toml."
    )


if __name__ == "__main__":
    raise SystemExit(hook_io.guard(decide))
