"""旁边有 pyproject.toml 时拦改 requirements.txt（通常 `uv export` 生成，引导改 pyproject.toml）。

纯路径判断，无状态依赖。
"""
from __future__ import annotations

from pathlib import Path

from lib.core.domain import FileChange, Finding, Severity, TargetKind
from lib.core.protocol import Rule


class RequirementsEditRule(Rule):
    name = "requirements-edit"
    target_kind = TargetKind.FILE_CHANGE

    def check(self, target: FileChange, ctx) -> list[Finding]:
        path = ctx.anchor_abspath or target.path
        if not path or Path(path).name != "requirements.txt":
            return []
        parent = Path(path).parent
        if not parent.is_absolute():
            return []
        if not any((d / "pyproject.toml").exists() for d in (parent, parent.parent)):
            return []
        return [
            Finding(
                rule=self.name,
                severity=Severity.DENY,
                message=(
                    f"⚠️  `{path}` is typically auto-generated by `uv export`, not hand-edited.\n"
                    "Edit `pyproject.toml` instead, then run `uv lock` + `uv sync`.\n"
                    "If CI needs requirements.txt, regenerate via `uv export` after editing pyproject.toml."
                ),
                locator=target.path,
            )
        ]
